# This is a TOML document
tite = "Configuration file for GTNH Config Helper"

[Settings]

[Config]
[Config.text.GT-Pollution]
file_path = '.minecraft/config/GregTech/Pollution.cfg'
use_regex = true
finds_str = 'B:"Activate Pollution"=true'
regex_str = 'B:"Activate Pollution"=(true|false)'
new_str = 'B:"Activate Pollution"=false'
# no side key = applies to both


[Config.text.GT-Pollution-Regex]
file_path = '.minecraft/config/GregTech/Pollution.cfg'
finds_str = 'B:"Activate Pollution"=(true|false)'
new_str = 'B:"Activate Pollution"=false'
use_regex = true


[Config.text.SomeClientOnlySetting]
file_path = '.minecraft/config/Something.cfg'
finds_str = 'render=true'
new_str = 'render=false'
side = "client"

[Config.text.SomeServerOnlySetting]
file_path = '.minecraft/config/Something.cfg'
finds_str = 'tickrate=20'
new_str = 'tickrate=40'
side = "server"
